import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Lexend, Poppins } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
	subsets: ['latin'],
	variable: '--font-lexend',
	display: 'swap',
})

const poppins = Poppins({
	subsets: ['latin'],
	variable: '--font-poppins',
	display: 'swap',
	weight: ['300', '400', '500', '600', '700'], // bebas, pilih range yang kamu butuh
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${lexend.variable} antialiased`}>
      <body
      ><StackProvider app={stackClientApp}><StackTheme>
        {children}
      </StackTheme></StackProvider></body>
    </html>
  );
}
